FROM node:20-alpine AS builder

WORKDIR /app

COPY web/package.json ./
RUN npm install

COPY web/src ./src
COPY web/next.config.mjs ./next.config.mjs
COPY web/tsconfig.json ./tsconfig.json
COPY web/postcss.config.mjs ./postcss.config.mjs

RUN npm run build

FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=8280

COPY --from=builder /app/package.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next

EXPOSE 8280

CMD ["npm", "start"]
